service: mock-dual-purpose-lambda

frameworkVersion: '>=1.41.1 <2.0.0'

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  profile: ${opt:profile}
  region: us-east-1

plugins:
  - serverless-step-functions

functions:
  logEvent:
    handler: handler.handler
    events:
      - http:
          path: lambda
          method: post

stepFunctions:
  stateMachines:
    logEventStepFunction:
      name: logEvent
      definition:
        StartAt: LogEvent
        States:
          LogEvent:
            Type: Task
            Resource: !GetAtt LogEventLambdaFunction.Arn
            End: true
      events:
        - http:
            path: stepfunction
            method: post
            request:
              template: lambda_proxy
